### ISSUE TITLE
next@canary + webpack 5 does not work in `target: "serverless"` mode

### ISSUE THREAD

**Issue by thomkrupa** [developit/nextjs-preact-demo#24] opened 2020-10-12 17:40 UTC
Hey, after upgrading next to `canary` and to webpack 5 the project stopped building. 

Here is the error:

```
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property '__H' of undefined
```

Repo with reproduction: https://github.com/thomkrupa/nextjs-preact-demo
Run: `yarn && yarn build`

**Comment by marvinhagemeister** [comment] 2020-10-26 07:27
This is resolved by upgrading `preact` and `preact-render-to-string` to the latest version. With that I can't reproduce the error anymore 👍

**Closed as completed by marvinhagemeister** 2020-10-26 07:27 UTC
